<?php
return [
    'dashboard'=>'Dashboard','pos'=>'POS','buy_scrap'=>'Buy Scrap','sell_scrap'=>'Sell Scrap','management'=>'Management',
    'purchases'=>'Purchases','sales'=>'Sales','inventory'=>'Inventory','stock_movement'=>'Stock Movement','materials'=>'Materials','customers'=>'Customers','suppliers'=>'Suppliers','expenses'=>'Expenses','reports'=>'Reports','logout'=>'Logout','settings'=>'Settings',
    'welcome'=>'Welcome','today_overview'=>"Today's business overview",'new_purchase'=>'New Purchase','today_purchase'=>"Today's Purchase",'today_sales'=>"Today's Sales",'today_expenses'=>"Today's Expenses",'today_profit'=>"Today's Profit",'business_performance'=>'Business performance','purchase_sales_trend'=>'Purchase vs sales trend','business_snapshot'=>'Business snapshot','stock_value'=>'Stock value','total_customers'=>'Customers','total_suppliers'=>'Suppliers','total_transactions'=>'Total transactions','recent_stock_movements'=>'Recent stock movements','time'=>'Time','material'=>'Material','type'=>'Type','quantity'=>'Quantity','stock_after'=>'Stock after','no_movements'=>'No movements yet. Start by buying scrap.',
    'fast_purchase_entry'=>'Fast purchase entry','stock_aware_selling'=>'Stock-aware selling','search_material'=>'Search material…','transaction_cart'=>'Transaction cart','select_material'=>'Select materials to begin.','subtotal'=>'Subtotal','discount'=>'Discount','other_cost'=>'Other cost','grand_total'=>'Grand total','customer_buyer'=>'Customer / Buyer','walk_in'=>'Walk-in customer','paid_amount'=>'Paid amount','payment_method'=>'Payment method','save_purchase'=>'Save Purchase','save_sale'=>'Save Sale','gross'=>'Gross','tare'=>'Tare','weight'=>'Weight','available'=>'Available','cash'=>'Cash','credit'=>'Credit',
    'scrap_materials'=>'Scrap Materials','prices_units'=>'Prices, units and stock thresholds','add_material'=>'Add material','search_code_material'=>'Search code or material name','code'=>'Code','category'=>'Category','buy'=>'Buy','sell'=>'Sell','stock'=>'Stock','delete'=>'Delete','material_name'=>'Material name','khmer_name'=>'Khmer name','purchase_price'=>'Purchase price','selling_price'=>'Selling price','minimum_stock'=>'Minimum stock','description'=>'Description','save_material'=>'Save material',
    'manage_contacts'=>'Manage contacts and outstanding balances','add'=>'Add','search_name_phone'=>'Search name or phone','name'=>'Name','phone'=>'Phone','address'=>'Address','balance'=>'Balance','contact_person'=>'Contact person','notes'=>'Notes','save'=>'Save',
    'current_stock'=>'Current Stock','inventory_overview'=>'Weighted-average inventory value and low-stock status','stock_adjustment'=>'Stock adjustment','average_cost'=>'Average cost','status'=>'Status','in_stock'=>'In stock','low_stock'=>'Low stock','out_of_stock'=>'Out of stock','add_stock'=>'Add stock','remove_stock'=>'Remove stock','damage'=>'Damage','loss'=>'Loss','correction'=>'Correction','reason'=>'Reason','date'=>'Date','save_adjustment'=>'Save adjustment','traceable'=>'Every inventory change is traceable','before'=>'Before','change'=>'Change','after'=>'After',
    'completed_history'=>'Completed :name history','new'=>'New','number'=>'Number','total'=>'Total','paid'=>'Paid','view'=>'View','receipt'=>'Receipt','print_receipt'=>'Print receipt','expense_costs'=>'Daily business costs','add_expense'=>'Add expense','record_expense'=>'Record expense','amount'=>'Amount','reports_overview'=>'Business performance using weighted-average cost','total_sales'=>'Total sales','total_purchases'=>'Total purchases','total_expenses'=>'Total expenses','net_profit'=>'Net profit','available_reports'=>'Available reports',
    'sign_in'=>'Sign in','email'=>'Email','password'=>'Password','remember'=>'Remember me','development_login'=>'Development: admin@example.com / password','language'=>'Language','english'=>'English','khmer'=>'ខ្មែរ',
    'receipt_business'=>'Scrap Buying & Selling · Cambodia','purchase_receipt'=>'Purchase Receipt','sale_receipt'=>'Sale Receipt','customer'=>'Customer','price'=>'Price',
];
