<?php
return [
    'dashboard'=>'ផ្ទាំងគ្រប់គ្រង','pos'=>'ការលក់','buy_scrap'=>'ទិញអេតចាយ','sell_scrap'=>'លក់អេតចាយ','management'=>'ការគ្រប់គ្រង',
    'purchases'=>'ការទិញ','sales'=>'ការលក់','inventory'=>'ស្តុក','stock_movement'=>'ចលនាស្តុក','materials'=>'សម្ភារៈអេតចាយ','customers'=>'អតិថិជន','suppliers'=>'អ្នកផ្គត់ផ្គង់','expenses'=>'ចំណាយ','reports'=>'របាយការណ៍','logout'=>'ចាកចេញ','settings'=>'ការកំណត់',
    'welcome'=>'សូមស្វាគមន៍','today_overview'=>'សង្ខេបអាជីវកម្មថ្ងៃនេះ','new_purchase'=>'ទិញថ្មី','today_purchase'=>'ការទិញថ្ងៃនេះ','today_sales'=>'ការលក់ថ្ងៃនេះ','today_expenses'=>'ចំណាយថ្ងៃនេះ','today_profit'=>'ចំណេញថ្ងៃនេះ','business_performance'=>'ដំណើរការអាជីវកម្ម','purchase_sales_trend'=>'ទំនោរការទិញ និងការលក់','business_snapshot'=>'ស្ថានភាពអាជីវកម្ម','stock_value'=>'តម្លៃស្តុក','total_customers'=>'អតិថិជន','total_suppliers'=>'អ្នកផ្គត់ផ្គង់','total_transactions'=>'ប្រតិបត្តិការសរុប','recent_stock_movements'=>'ចលនាស្តុកថ្មីៗ','time'=>'ពេលវេលា','material'=>'សម្ភារៈ','type'=>'ប្រភេទ','quantity'=>'បរិមាណ','stock_after'=>'ស្តុកនៅសល់','no_movements'=>'មិនទាន់មានចលនាស្តុកទេ។ សូមចាប់ផ្តើមដោយទិញអេតចាយ។',
    'fast_purchase_entry'=>'បញ្ចូលការទិញរហ័ស','stock_aware_selling'=>'លក់ដោយត្រួតពិនិត្យស្តុក','search_material'=>'ស្វែងរកសម្ភារៈ…','transaction_cart'=>'កន្ត្រកប្រតិបត្តិការ','select_material'=>'ជ្រើសរើសសម្ភារៈដើម្បីចាប់ផ្តើម។','subtotal'=>'សរុប','discount'=>'បញ្ចុះតម្លៃ','other_cost'=>'ចំណាយផ្សេងៗ','grand_total'=>'សរុបចុងក្រោយ','customer_buyer'=>'អតិថិជន / អ្នកទិញ','walk_in'=>'អតិថិជនដើរចូល','paid_amount'=>'ប្រាក់បានបង់','payment_method'=>'វិធីបង់ប្រាក់','save_purchase'=>'រក្សាទុកការទិញ','save_sale'=>'រក្សាទុកការលក់','gross'=>'ទម្ងន់សរុប','tare'=>'ទម្ងន់បាវ','weight'=>'ទម្ងន់','available'=>'មានស្រាប់','cash'=>'សាច់ប្រាក់','credit'=>'ជំពាក់',
    'scrap_materials'=>'សម្ភារៈអេតចាយ','prices_units'=>'តម្លៃ ឯកតា និងកម្រិតស្តុកអប្បបរមា','add_material'=>'បន្ថែមសម្ភារៈ','search_code_material'=>'ស្វែងរកកូដ ឬឈ្មោះសម្ភារៈ','code'=>'កូដ','category'=>'ប្រភេទ','buy'=>'ទិញ','sell'=>'លក់','stock'=>'ស្តុក','delete'=>'លុប','material_name'=>'ឈ្មោះសម្ភារៈ','khmer_name'=>'ឈ្មោះខ្មែរ','purchase_price'=>'តម្លៃទិញ','selling_price'=>'តម្លៃលក់','minimum_stock'=>'ស្តុកអប្បបរមា','description'=>'ការពិពណ៌នា','save_material'=>'រក្សាទុកសម្ភារៈ',
    'manage_contacts'=>'គ្រប់គ្រងទំនាក់ទំនង និងសមតុល្យជំពាក់','add'=>'បន្ថែម','search_name_phone'=>'ស្វែងរកឈ្មោះ ឬលេខទូរស័ព្ទ','name'=>'ឈ្មោះ','phone'=>'ទូរស័ព្ទ','address'=>'អាសយដ្ឋាន','balance'=>'សមតុល្យ','contact_person'=>'អ្នកទំនាក់ទំនង','notes'=>'កំណត់ចំណាំ','save'=>'រក្សាទុក',
    'current_stock'=>'ស្តុកបច្ចុប្បន្ន','inventory_overview'=>'តម្លៃស្តុកតាមតម្លៃមធ្យម និងស្ថានភាពស្តុក','stock_adjustment'=>'កែតម្រូវស្តុក','average_cost'=>'តម្លៃមធ្យម','status'=>'ស្ថានភាព','in_stock'=>'មានក្នុងស្តុក','low_stock'=>'ស្តុកតិច','out_of_stock'=>'អស់ស្តុក','add_stock'=>'បន្ថែមស្តុក','remove_stock'=>'ដកស្តុក','damage'=>'ខូចខាត','loss'=>'បាត់បង់','correction'=>'កែតម្រូវ','reason'=>'មូលហេតុ','date'=>'កាលបរិច្ឆេទ','save_adjustment'=>'រក្សាទុកការកែតម្រូវ','traceable'=>'រាល់ការផ្លាស់ប្តូរស្តុកអាចតាមដានបាន','before'=>'មុន','change'=>'បម្រែបម្រួល','after'=>'ក្រោយ',
    'completed_history'=>'ប្រវត្តិ :name ដែលបានបញ្ចប់','new'=>'ថ្មី','number'=>'លេខ','total'=>'សរុប','paid'=>'បានបង់','view'=>'មើល','receipt'=>'បង្កាន់ដៃ','print_receipt'=>'បោះពុម្ពបង្កាន់ដៃ','expense_costs'=>'ចំណាយប្រចាំថ្ងៃរបស់អាជីវកម្ម','add_expense'=>'បន្ថែមចំណាយ','record_expense'=>'កត់ត្រាចំណាយ','amount'=>'ចំនួនទឹកប្រាក់','reports_overview'=>'ដំណើរការអាជីវកម្មតាមតម្លៃមធ្យម','total_sales'=>'ការលក់សរុប','total_purchases'=>'ការទិញសរុប','total_expenses'=>'ចំណាយសរុប','net_profit'=>'ចំណេញសុទ្ធ','available_reports'=>'របាយការណ៍ដែលមាន',
    'sign_in'=>'ចូលប្រើ','email'=>'អ៊ីមែល','password'=>'ពាក្យសម្ងាត់','remember'=>'ចងចាំខ្ញុំ','development_login'=>'សម្រាប់អភិវឌ្ឍ៖ admin@example.com / password','language'=>'ភាសា','english'=>'English','khmer'=>'ខ្មែរ',
    'receipt_business'=>'ទិញ និងលក់អេតចាយ · កម្ពុជា','purchase_receipt'=>'បង្កាន់ដៃទិញ','sale_receipt'=>'បង្កាន់ដៃលក់','customer'=>'អតិថិជន','price'=>'តម្លៃ',
];
