<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('users', function(Blueprint $t){$t->id();$t->string('name');$t->string('email')->unique();$t->string('password');$t->rememberToken();$t->timestamps();});
  Schema::create('units', function(Blueprint $t){$t->id();$t->string('name');$t->string('symbol',12);$t->boolean('status')->default(true);$t->timestamps();});
  Schema::create('material_categories', function(Blueprint $t){$t->id();$t->string('name')->unique();$t->string('khmer_name')->nullable();$t->text('description')->nullable();$t->boolean('status')->default(true);$t->timestamps();});
  Schema::create('materials', function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('name');$t->string('khmer_name')->nullable();$t->foreignId('category_id')->constrained('material_categories');$t->foreignId('unit_id')->constrained();$t->decimal('purchase_price',14,4)->default(0);$t->decimal('selling_price',14,4)->default(0);$t->decimal('current_stock',14,3)->default(0);$t->decimal('average_cost',14,4)->default(0);$t->decimal('minimum_stock',14,3)->default(0);$t->string('image')->nullable();$t->text('description')->nullable();$t->boolean('status')->default(true);$t->timestamps();});
  Schema::create('customers', function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('name');$t->string('phone')->nullable();$t->text('address')->nullable();$t->string('type')->default('Individual');$t->text('notes')->nullable();$t->decimal('outstanding_balance',14,2)->default(0);$t->timestamps();});
  Schema::create('suppliers', function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('name');$t->string('phone')->nullable();$t->text('address')->nullable();$t->string('contact_person')->nullable();$t->text('notes')->nullable();$t->decimal('outstanding_balance',14,2)->default(0);$t->boolean('status')->default(true);$t->timestamps();});
  Schema::create('purchases', function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('supplier_id')->nullable()->constrained()->nullOnDelete();$t->dateTime('purchased_at');$t->decimal('total_weight',14,3)->default(0);$t->decimal('subtotal',14,2);$t->decimal('discount',14,2)->default(0);$t->decimal('other_cost',14,2)->default(0);$t->decimal('grand_total',14,2);$t->decimal('amount_paid',14,2)->default(0);$t->decimal('balance',14,2)->default(0);$t->string('payment_method')->default('Cash');$t->string('status')->default('completed');$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('purchase_items', function(Blueprint $t){$t->id();$t->foreignId('purchase_id')->constrained()->cascadeOnDelete();$t->foreignId('material_id')->constrained();$t->decimal('gross_weight',14,3);$t->decimal('tare_weight',14,3)->default(0);$t->decimal('net_weight',14,3);$t->decimal('unit_price',14,2);$t->decimal('subtotal',14,2);$t->decimal('cost_per_unit',14,2);$t->timestamps();});
  Schema::create('sales', function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->dateTime('sold_at');$t->decimal('total_weight',14,3)->default(0);$t->decimal('subtotal',14,2);$t->decimal('discount',14,2)->default(0);$t->decimal('other_cost',14,2)->default(0);$t->decimal('grand_total',14,2);$t->decimal('amount_paid',14,2)->default(0);$t->decimal('balance',14,2)->default(0);$t->decimal('cost_of_goods',14,2)->default(0);$t->string('payment_method')->default('Cash');$t->string('status')->default('completed');$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('sale_items', function(Blueprint $t){$t->id();$t->foreignId('sale_id')->constrained()->cascadeOnDelete();$t->foreignId('material_id')->constrained();$t->decimal('weight',14,3);$t->decimal('unit_price',14,2);$t->decimal('subtotal',14,2);$t->decimal('cost_per_unit',14,2);$t->decimal('cost_total',14,2);$t->timestamps();});
  Schema::create('stock_movements', function(Blueprint $t){$t->id();$t->foreignId('material_id')->constrained();$t->string('type');$t->decimal('quantity',14,3);$t->decimal('stock_before',14,3);$t->decimal('stock_after',14,3);$t->decimal('unit_cost',14,2)->default(0);$t->string('reference_type')->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->text('reason')->nullable();$t->dateTime('moved_at');$t->timestamps();});
  Schema::create('stock_adjustments', function(Blueprint $t){$t->id();$t->foreignId('material_id')->constrained();$t->string('type');$t->decimal('quantity',14,3);$t->decimal('stock_before',14,3);$t->decimal('stock_after',14,3);$t->text('reason');$t->date('adjusted_at');$t->timestamps();});
  Schema::create('expense_categories', function(Blueprint $t){$t->id();$t->string('name')->unique();$t->boolean('status')->default(true);$t->timestamps();});
  Schema::create('expenses', function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('expense_category_id')->constrained();$t->text('description')->nullable();$t->decimal('amount',14,2);$t->date('expense_date');$t->string('payment_method')->default('Cash');$t->string('receipt_image')->nullable();$t->timestamps();});
  Schema::create('payments', function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('purchase_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('sale_id')->nullable()->constrained()->nullOnDelete();$t->decimal('amount',14,2);$t->string('payment_method');$t->dateTime('paid_at');$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('cash_registers', function(Blueprint $t){$t->id();$t->date('register_date')->unique();$t->decimal('opening_cash',14,2)->default(0);$t->decimal('actual_closing_cash',14,2)->nullable();$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('settings', function(Blueprint $t){$t->id();$t->string('key')->unique();$t->text('value')->nullable();$t->timestamps();});
 }
 public function down(): void { foreach(['settings','cash_registers','payments','expenses','expense_categories','stock_adjustments','stock_movements','sale_items','sales','purchase_items','purchases','suppliers','customers','materials','material_categories','units','users'] as $table) Schema::dropIfExists($table); }
};
